version: '3.7'


x-db-config: &db-config
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_PORT: ${DATABASE_PORT}
  DATABASE_USER: ${POSTGRES_USER}
  DATABASE_PASSWORD: ${POSTGRES_PASSWORD}

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - mynetwork
    depends_on:
      - pgadmin
    env_file:
      - .env
    volumes:
      - ./fabotrix:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    command: python run_api.py

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - api
    networks:
      - mynetwork
    volumes:
      - ./fabotrix:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    env_file:
      - .env
    command: python run_bot.py

  db:
    image: postgres:15.2-alpine
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - mynetwork
    depends_on:
      - db


networks:
  mynetwork:
    driver: bridge
